#! /bin/bash

KIT_FILE=blog-$1
TINYMCE_VER=3.3.9.4
TINYMCE_COMPRESSOR_VER=2_0_3

cd /websites/LinuxPackage02/el/li/so/ellisons.org.uk/public_html/blog

# remove all blog subdirectories except images
rm -R $(ls | grep  -v images)

# and replace working subdirectories
mkdir --parents _admin _cache html_cache includes/tinymce /tmp/tmp$$


unzip -x  ../_private/kits/tinymce_$TINYMCE_VER.zip -d /tmp/tmp$$
unzip -x  ../_private/kits/tinymce_compressor_php_$TINYMCE_COMPRESSOR_VER.zip -d /tmp/tmp$$
mv /tmp/tmp$$/tinymce/jscripts/tiny_mce/* includes/tinymce
mv /tmp/tmp$$/tinymce_compressor_php/tiny_mce_gzip.{php,js} includes/tinymce
rm -R /tmp/tmp$$

# unpack kits tarball
tar -xjf ../_private/kits/$KIT_FILE.tar.bz2 
cp -r _misc/tinymce/* includes/tinymce

#remove Apache access to private directories; these are still accessible via suPHP
chmod -R 700  _admin _cache _include _template _misc

# compress the CSS 
perl - themes/terry/all.css <<'END_PERL' > /tmp/all.css
  undef $/;  $_=scalar(<>);
  s!/\*.*?\*/!!gs; 
  s![\n\s]+! !gs;
  s/ ?([{}#:;!,>]) ?/\1/g;
  s/;}/}\n/g;
  s/;/;\n\t/g;
  print;
END_PERL
mv /tmp/all.css themes/terry/all.css

source _misc/config
sed -i -e "s/host:db:user:pwd:prefix_/$CONNECT_CFG/" index.php

chmod -R  o=rX,g=rX docs html_cache images includes themes
chmod 600 index.php

